
#
# Module Manifest for Module 'PsoDownloader.psd1
#
# This manifest file is a PowerShell hashtable with all technical requirements for this module
# This module was autogenerated by ISESteroids (http://www.isesteroids.com)
#
# Generated: 2022-06-08
#

@{

# Module Loader File
RootModule = 'loader.psm1'

# Version Number
ModuleVersion = '1.0.0'

# Unique Module ID
GUID = 'ff08e6e2-ddf3-41a4-9d1e-c5197cbe076c'

# Module Author
Author = 'Dr. Tobias Weltner'

# Company
CompanyName = 'powershell.one'

# Copyright
Copyright = 'created 2022 by Dr. Tobias Weltner, free public domain license, http://unlicense.org'

# Module Description
Description = 'A simple PowerShell cmdlet to download all kinds of Internet resources including streaming media'

# Minimum PowerShell Version Required
PowerShellVersion = ''

# Name of Required PowerShell Host
PowerShellHostName = ''

# Minimum Host Version Required
PowerShellHostVersion = ''

# Minimum .NET Framework-Version
DotNetFrameworkVersion = ''

# Minimum CLR (Common Language Runtime) Version
CLRVersion = ''

# Processor Architecture Required (X86, Amd64, IA64)
ProcessorArchitecture = ''

# Required Modules (will load before this module loads)
RequiredModules = @()

# Required Assemblies
RequiredAssemblies = @()

# PowerShell Scripts (.ps1) that need to be executed before this module loads
ScriptsToProcess = @()

# Type files (.ps1xml) that need to be loaded when this module loads
#TypesToProcess = @()

# Format files (.ps1xml) that need to be loaded when this module loads
#FormatsToProcess = @()

# 
#NestedModules = @()

# List of exportable functions
FunctionsToExport = 'Invoke-DownloadFile'

# List of exportable cmdlets
#CmdletsToExport = '*'

# List of exportable variables
#VariablesToExport = '*'

# List of exportable aliases
AliasesToExport = '*'

# List of all modules contained in this module
#ModuleList = @()

# List of all files contained in this module
#FileList = @()

# Private data that needs to be passed to this module
#PrivateData = ''

}